window:
 title: Alacritty
 dimensions:
    columns: 120
    lines: 50


# Font configuration (changes require restart)
font:
  # Normal (roman) font face
  normal:
    # family: Source Code Pro for Powerline
    family: SourceCodePro
    # The `style` can be specified to pick a specific face.
    style: Regular

  # Italic font face
  bold:
    # family: Source Code Pro for Powerline
    family: SourceCodePro
    # The `style` can be specified to pick a specific face.
    style: Bold

  # Italic font face
  italic:
    # family: Source Code Pro for Powerline
    family: SourceCodePro
    # The `style` can be specified to pick a specific face.
    style: Italic

  # Point size
  size: 12.0

  # Offset is the extra space around each character. `offset.y` can be thought of
  # as modifying the line spacing, and `offset.x` as modifying the letter spacing.
  offset:
    x: 0
    y: 0

  # Glyph offset determines the locations of the glyphs within their cells with
  # the default being at the bottom. Increasing `x` moves the glyph to the right,
  # increasing `y` moves the glyph upwards.
  glyph_offset:
    x: 0
    y: 0

  # Scale the font size based on the monitor's DPI. This will lead to bigger text on HiDPI
  # screens and make reading text a little easier.
  scale_with_dpi: true

draw_bold_text_with_bright_colors: true

background_opacity: 0.8
dynamic_title: true

# Cursor style
# Valid values
#  - Block
#  - Underline
#  - Beam
cursor_style: Block

