import = [
  "~/dotfiles/config/alacritty/themes/cattpuchin-macchiato.toml",
  # "~/dotfiles/config/alacritty/themes/cattpuchin-latte.toml",
  "~/dotfiles/config/alacritty/keybindings.toml",
]

[colors]
draw_bold_text_with_bright_colors = true

[font]
size = 10.0

[font.bold]
# family = "SourceCodePro"
family = "FiraCode NerdFont"
style = "Bold"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
# family = "SourceCodePro"
family = "FiraCode NerdFont"
style = "Italic"

[font.normal]
family = "FiraCode NerdFont"
# family = "SourceCodePro"
style = "Regular"

[font.offset]
x = 0
y = 0

[window]
decorations = "Full"
title = "Alacritty"

[window.dimensions]
columns = 120
lines = 50

[window.padding]
x = 0
y = 0
