import = [
    # "~/dotfiles/config/alacritty/themes/cattpuchin-macchiato.toml",
    # "~/dotfiles/config/alacritty/themes/cattpuchin-latte.toml",
]

[colors]
draw_bold_text_with_bright_colors = true

[font]
size = 11.0

[font.bold]
family = "SourceCodePro"
style = "Bold"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "SourceCodePro"
style = "Italic"

[font.normal]
family = "SourceCodePro"
style = "Regular"

[font.offset]
x = 0
y = 0

[window]
decorations = "Full"
title = "Alacritty"

[window.dimensions]
columns = 120
lines = 50

[window.padding]
x = 0
y = 0
