window:
  title: Alacritty
  dimensions:
    columns: 120
    lines: 50
  padding:
    x: 0
    y: 0
  decorations: Full


  # Font configuration (changes require restart)
font:
  # Normal (roman) font face
  normal:
    # family: Source Code Pro for Powerline
    family: SourceCodePro
    # The `style` can be specified to pick a specific face.
    style: Regular

  # Bold font face
  bold:
    # family: Source Code Pro for Powerline
    family: SourceCodePro
    # The `style` can be specified to pick a specific face.
    style: Bold

  # Italic font face
  italic:
    # family: Source Code Pro for Powerline
    family: SourceCodePro
    # The `style` can be specified to pick a specific face.
    style: Italic

  # Point size
  size: 11.0

  # Offset is the extra space around each character. `offset.y` can be thought of
  # as modifying the line spacing, and `offset.x` as modifying the letter spacing.
  offset:
    x: 0
    y: 0

  # Glyph offset determines the locations of the glyphs within their cells with
  # the default being at the bottom. Increasing `x` moves the glyph to the right,
  # increasing `y` moves the glyph upwards.
  glyph_offset:
    x: 0
    y: 0

  # Scale the font size based on the monitor's DPI. This will lead to bigger text on HiDPI
  # screens and make reading text a little easier.
  scale_with_dpi: true

draw_bold_text_with_bright_colors: true

window.opacity: 0.8
dynamic_title: true

# Cursor style
# Valid values
#  - Block
#  - Underline
#  - Beam
cursor_style: Block


themes:

  # Nightfox Alacritty Colors
  # Style: nordfox
  # Upstream: https://github.com/edeneast/nightfox.nvim/raw/main/extra/nordfox/nightfox_alacritty.yml
  nordfox: &nordfox
    cursor:
      #text: CellBackground
      #cursor: '#002b36'
      text: CellBackground
      Cursor: CellForeground
    # Default colors
    primary:
      background: '0x2e3440'
      foreground: '0xb9bfca'
    # Normal colors
    normal:
      black:   '0x3b4252'
      red:     '0xbf616a'
      green:   '0xa3be8c'
      yellow:  '0xebcb8b'
      blue:    '0x81a1c1'
      magenta: '0xb48ead'
      cyan:    '0x88c0d0'
      white:   '0xe5e9f0'
    # Bright colors
    bright:
      black:   '0x465780'
      red:     '0xd06f79'
      green:   '0xb1d196'
      yellow:  '0xf0d399'
      blue:    '0x8cafd2'
      magenta: '0xc895bf'
      cyan:    '0x93ccdc'
      white:   '0xe7ecf4'
    indexed_colors:
      - { index: 16, color: '0xc9826b' }
      - { index: 17, color: '0xbf88bc' }
    draw_bold_text_with_bright_colors: false

  # Nightfox Alacritty Colors
  # Style: dawnfox
  # Upstream: https://github.com/edeneast/nightfox.nvim/raw/main/extra/dawnfox/nightfox_alacritty.yml
  dawnfox: &dawnfox
    cursor:
      #text: CellBackground
      #cursor: '#002b36'
      text: CellBackground
      Cursor: CellForeground
    # Default colors
    primary:
      background: '0xfaf4ed'
      foreground: '0x575279'
    # Normal colors
    normal:
      black:   '0x575279'
      red:     '0xb4637a'
      green:   '0x618774'
      yellow:  '0xea9d34'
      blue:    '0x286983'
      magenta: '0x907aa9'
      cyan:    '0x56949f'
      white:   '0xe5e9f0'
    # Bright colors
    bright:
      black:   '0x5f5695'
      red:     '0xc26d85'
      green:   '0x629f81'
      yellow:  '0xeea846'
      blue:    '0x2d81a3'
      magenta: '0x9a80b9'
      cyan:    '0x5ca7b4'
      white:   '0xe6ebf3'
    indexed_colors:
      - { index: 16, color: '0xd7827e' }
      - { index: 17, color: '0xd685af' }

  # Base16 Gruvbox dark, medium 256 - alacritty color config
  # Dawid Kurek (dawikur@gmail.com), morhetz (https://github.com/morhetz/gruvbox)
  gruvbox: &gruvbox
    cursor:
      #text: CellBackground
      #cursor: '#002b36'
      text: CellBackground
      Cursor: CellForeground
    # Default colors
    primary:
      background: '0x282828'
      foreground: '0xd5c4a1'

    # Colors the cursor will use if `custom_cursor_colors` is true
    cursor:
      text: '0x282828'
      cursor: '0xd5c4a1'

    # Normal colors
    normal:
      black:   '0x282828'
      red:     '0xfb4934'
      green:   '0xb8bb26'
      yellow:  '0xfabd2f'
      blue:    '0x83a598'
      magenta: '0xd3869b'
      cyan:    '0x8ec07c'
      white:   '0xd5c4a1'

    # Bright colors
    bright:
      black:   '0x665c54'
      red:     '0xfb4934'
      green:   '0xb8bb26'
      yellow:  '0xfabd2f'
      blue:    '0x83a598'
      magenta: '0xd3869b'
      cyan:    '0x8ec07c'
      white:   '0xfbf1c7'

    indexed_colors:
      - { index: 16, color: '0xfe8019' }
      - { index: 17, color: '0xd65d0e' }
      - { index: 18, color: '0x3c3836' }
      - { index: 19, color: '0x504945' }
      - { index: 20, color: '0xbdae93' }
      - { index: 21, color: '0xebdbb2' }

    draw_bold_text_with_bright_colors: false

# some are at https://github.com/eendroroy/alacritty-theme

colors: *nordfox
