
[colors]
draw_bold_text_with_bright_colors = false

[font]
size = 12

[font.normal]
# family = "SourceCodePro"
family = "JetBrainsMono Nerd Font"
# family = "UbuntuMonoNerdFont"
style = "Regular"

[font.bold]
# family = "SourceCodePro"
family = "JetBrainsMono Nerd Font"
# family = "UbuntuMonoNerdFont"
style = "Bold"

[font.italic]
# family = "SourceCodePro"
family = "JetBrainsMono Nerd Font"
# family = "UbuntuMonoNerdFont"
style = "Italic"

[font.glyph_offset]
x = 0
y = 0

[font.offset]
x = 0
y = 0

[window]
decorations = "Full"
title = "Alacritty"

[window.dimensions]
columns = 120
lines = 50

[window.padding]
x = 0
y = 0

[general]
import = [
  # "~/dotfiles/config/alacritty/themes/cattpuchin-macchiato.toml",
  "~/dotfiles/config/alacritty/themes/nightfox.toml",
  # "~/dotfiles/config/alacritty/themes/cattpuchin-latte.toml",
  "~/dotfiles/config/alacritty/keybindings.toml",
]
