[keyboard]
bindings = [
  { key = "N", mods = "Control|Shift", action = "CreateNewWindow" },
  # { key = "F", mods = "Control", action = "SearchForward" },
  { key = "F", mods = "Control|Shift", action = "SearchBackward" },
]
