
# Fonts
font_family		MesloLGS NF
italic_font		auto
bold_font		auto
bold_italic_font	auto
font_size		12

# Terminal bell
enable_audio_bell	yes
visual_bell_duration	0.0
window_alert_on_bell	yes
bell_on_tab		yes

# Window
remember_window_size	no
initial_window_width    1200
initial_window_height   800
window_border_width	1
window_margin_width	3
placement_strategy	center
background_opacity	0.80

# Tabs
tab_bar_edge		top
tab_bar_style		separator
active_tab_font_style	italic

# Monitor
sync_to_monitor		yes
