require("config.env_vars")
require("config.autostart")
require("config.keybinds")
require("config.monitors")
require("config.rules")
require("config.config")
require("config.inputs")
require("config.animations")
