# autogenerated by txs
#include:expl3
\__hook expl3#S
\clist_put_right:Nv#S
\keys_if_exist:nxT#S
\keys_if_exist:nxTF#S
\msg extra text > keyvalue/option-unknown#S
\msg text > keyvalue/option-unknown#S
\unprocessedoptions-expl3.sty#S
csnameendcsname#S
expl3.sty#S
